build:
  nodes:
    php80:
      environment:
        php: 8.0
        redis: false
      dependencies:
        before:
          - command: 'pecl install openswoole'
    analysis:
      tests:
        override:
          - php-scrutinizer-run