version: '3.1'
services:
    migration:
        image: flyway/flyway:latest
        volumes:
            - ./src/Impl/Db/Resources/Postgresql:/flyway/sql
        command: "-url=jdbc:postgresql://172.24.64.93:5432/engine -schemas=public -baselineOnMigrate=true -user=postgres -password=postgres -connectRetries=60 migrate" 