version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=bpm_engine
        ports:
            - 7432:5432
    migration:
        image: flyway/flyway:latest
        volumes:
            - ./db/postgres:/flyway/sql
        command: "-url=jdbc:postgresql://db:5432/bpm_engine -schemas=bpm_engine -baselineOnMigrate=true -user=postgres -password=postgres -connectRetries=60 migrate"
        depends_on:
            - db   