version: '3.9'
services:
  mysql_db:
    image: mysql:8.1.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: engine
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  migration:
    build: ./Migration
    depends_on:
      wait-for-db:
        condition: service_completed_successfully 
    volumes:
      - ../../src/Resources/Db/MySQL:/flyway/sql
    command: "-url=jdbc:mysql://mysql_db:3306?allowPublicKeyRetrieval=true&useSSL=false -schemas=engine -user=test -password=test -connectRetries=60 migrate"    
  starter:
    build: ./EngineStarterService
    restart: always
    depends_on:
      wait-for-db:
        condition: service_completed_successfully 
    environment:
      DB_JABE_DRIVER: pdo_mysql
      DB_JABE_HOST: mysql_db
      DB_JABE_PORT: 3306
      DB_JABE_USER: test
      DB_JABE_PASSWORD: test
      DB_JABE_NAME: engine
  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - mysql_db
    command: tcp mysql_db:3306 -t 30s -i 250ms      